#------------------------------------------------------------------------------
#
# MEAN 開発環境の構築
#
#------------------------------------------------------------------------------
version: "3.2"
services:

  #
  # Frontend Webserver container
  #
  xtechlog-frontend:
    image: node
    container_name: xtechlog-frontend
    tty: true
    user: node
    volumes:
      - ./frontend/app:/home/app
    working_dir: /home/app
    ports:
      - 8080:8080
    networks:
      - xtechlog-webnet
    depends_on:
      - xtechlog-mongo
      - xtechlog-backend
    links:
      - xtechlog-backend

  #
  # Backend Server container
  #
  xtechlog-backend:
    image: node
    container_name: xtechlog-backend
    tty: true
    user: node
    volumes:
      - ./backend/app:/home/app
    working_dir: /home/app
    ports:
      - 3000:3000
    networks:
      - xtechlog-webnet
    depends_on:
      - xtechlog-mongo
    links:
      - xtechlog-mongo

  #
  # MongoDB container
  #
  # ルート権限をもつユーザー・パスワードを登録 
  # ($MONGO_INITDB_ROOT_USERNAME, $MONGO_INITDB_ROOT_PASSWORD)
  # DBを作成　(DB名は${MONGO_INITDB_DATABASE)
  #
  # docker-compose up -d　の実行時に
  # ./mongo/docker-entrypoint-initdb.d/init.js を実行
  # データベースの一般ユーザー登録、初期データ搭載 
  #
  xtechlog-mongo:
    image: mongo
    container_name: xtechlog-mongo
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    networks:
      - xtechlog-webnet

  #
  # MongoDB GUI Client container
  #
  xtechlog-mongo-express:
    image: mongo-express
    container_name: xtechlog-mongo-express
    ports:
      - 8081:8081
    networks:
      - xtechlog-webnet
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: xtechlog-mongo
      ME_CONFIG_BASICAUTH_UERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - xtechlog-mongo
    links:
      - xtechlog-mongo
  
networks:
  xtechlog-webnet:

